### ISSUE TITLE
Tag release for lists usage

### ISSUE THREAD

**Issue by Christophvh** [testmonitor/activecampaign#21]
Hi,

Thanks for the package! 

Would it be possible to tag a release for the list API? Currently I need to install this packages as 'dev-master' which is a bit unsafe.

**Comment by thijskok** [comment]
Hi,

Sure! I plan to release a new version today.

**Comment by Christophvh** [comment]
thanks!

**Comment by thijskok** [comment]
Tagged, thanks for your contribution!
