### ISSUE TITLE
Custom Field values

### ISSUE THREAD

**Issue by Jamesking56** [testmonitor/activecampaign#23]
How do I get the values of Custom Fields that are attached to a contact?

**Comment by zebrastribe** [comment]
I would like to know that as well ... The findContact() function does not include the fieldValues. Did you find a solution?

**Comment by Jamesking56** [comment]
I did find a solution in the end by grabbing them out of the main contact record. They are available under a `custom_fields` object

**Comment by wdelfuego** [comment]
Hi @Jamesking56, I’m running into this as well but can’t find the ‘custom_fields’ object you refer to. Any chance you can share a bit of code to show how you get custom field values given a Contact object? It’s been a while, not sure if your comment still applies to v3 of the api. 

Thanks for any help!
