### ISSUE TITLE
contactsByList only returns 20 contacts maximum

### ISSUE THREAD

**Issue by Jamesking56** [testmonitor/activecampaign#24]
The `contactsByList` method only returns 20 contacts, I believe this is because the ActiveCampaign API is paginated and this method only ever returns the first page.

**Comment by stefanius** [comment]
@Jamesking56 Sorry for this late answer. If this still an issue feel free to send us a PR.

**Comment by stefanius** [comment]
For now I will close this issue.

**Comment by seanBlommaert** [comment]
I created a PR for this: #36
