### ISSUE TITLE
Missing functionality

### ISSUE THREAD

**Issue by treehousetim** [testmonitor/activecampaign#27]
I'm curious if you'd accept PRs for missing functionality to do things like 

Remove a tag from a contact.
https://developers.activecampaign.com/reference/remove-a-contacts-tag

Retrieve a field value for a contact
https://developers.activecampaign.com/reference/retrieve-contact-field-values

Thanks,

- Tim

**Comment by thijskok** [comment]
> I'm curious if you'd accept PRs for missing functionality to do things like
> 
> Remove a tag from a contact. https://developers.activecampaign.com/reference/remove-a-contacts-tag
> 
> Retrieve a field value for a contact https://developers.activecampaign.com/reference/retrieve-contact-field-values
> 
> Thanks,
> 
> * Tim

Hi @treehousetim,

Sure, feel free to create a PR!

**Comment by Frankisgek** [comment]
Hi @treehousetim,

Thank you for your interest in contributing to this project. Unfortunately, we are no longer maintaining this package, and we have decided to abandon it. As a result, we will not be addressing any further issues or pull requests. I will therefore close this issue.
