### ISSUE TITLE
Making a custom request?

### ISSUE THREAD

**Issue by MCKLtech** [testmonitor/activecampaign#30]
I hoping to use this library as a jump-off point, but I need to make some requests that it doesn't support. For example, connections:

https://developers.activecampaign.com/reference/create-connection

I tried to make a request, but ActiveCampaign is responding that required parameters, such as name, are not being passed, even though they are in the payload:

```
$payload = [
		'service' => 'My Great Connector'
		'externalid' => 'amneCorp,
		'name' => 'My Great Connector',
		'linkUrl' => 'https://www.example.com,
		'logoUrl' => 'https://via.placeholder.com/150'
	];

$connection = $activeCampaign->guzzle->request('POST', 'connections', ['connection' => $payload]);

```

Any ideas why this would not be working? GET requests work perfectly, it seems to be the POST requests that fail, almost as if the body is never sent.

**Comment by MCKLtech** [comment]
My bad, took a second look and you need to pass the JSON parameter to Guzzle. This works:

```
$connection = $activeCampaign->guzzle->request( 'POST', 'connections', [ 'json' => [ 'connection' => $payload ] ] );
```
Might be worth adding this to the ReadME? Would be helpful for missing end points.

**Comment by rharish101** [comment]
Alternately, could we have the methods of `MakesHttpRequests` in `src/MakesHttpRequests.php` be public?

**Comment by Frankisgek** [comment]
Hi @MCKLtech @rharish101,

Unfortunately, we are no longer maintaining this package, and we have decided to abandon it. As a result, we will not be addressing any further issues or pull requests. I will therefore close this issue.

We encourage the community to fork the repository if you'd like to continue development or take the project in a new direction. Thank you for your understanding.
