### ISSUE TITLE
Allow passing custom field values to createContact / findOrCreateContact / updateOrCreateContact

### ISSUE THREAD

**Issue by seanBlommaert** [testmonitor/activecampaign#33]
To reduce the number of API calls needed to create a full contact in Active Campain, the API supports passing fieldValues when creating or syncing a contact. It would be nice if this library supports this.

https://developers.activecampaign.com/reference/create-a-new-contact
https://developers.activecampaign.com/reference/sync-a-contacts-data

**Comment by seanBlommaert** [comment]
I created a PR #34 that seems to work for me. Would this be something worth adding?

**Comment by Frankisgek** [comment]
Hi @seanBlommaert,

Unfortunately, we are no longer maintaining this package, and we have decided to abandon it. As a result, we will not be addressing any further issues or pull requests. I will therefore close this issue.

We encourage the community to fork the repository if you'd like to continue development or take the project in a new direction. Thank you for your understanding.
